apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/images.class: nginx
    ngnix.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: posts.com 
      http:
        paths:
          - path: /posts-create
            backend:
              serviceName: posts-service
              servicePort: 4000
          - path: /posts
            backend:
              serviceName: query-service
              servicePort: 4002
          - path: /posts/?(.*)/comments
            backend:
              serviceName: comments-service
              servicePort: 4001
          - path: /?(.*)
            backend:
              serviceName: client-service
              servicePort: 3000